### ISSUE TITLE
how to know if the key exists ?

### ISSUE THREAD

**Issue by poplk** [jeffbski/redis-rstream#2]
Hi,

This is certainly a stupid question, but I can't figure out, using redisRStream, how to know if the key exists in Redis ?
I am using redisRStream to stream directly a jpeg content stored in redis to http response, this works brillantly, but when the key does not exist, I want to put the jpeg in redis.
The only way I found, is to try a normal node_redis GET before, but this is a waste !
Any idea ?

**Comment by jeffbski** [comment]
Well one way is with "exists"

http://redis.io/commands/exists

**Comment by poplk** [comment]
sure ... one way is always reading the documentation ;) ... Thanks a lot Jeff :)

**Comment by jeffbski** [comment]
Yeah, where's the fun in that. :-)

You are welcome. Glad I could help.
