### ISSUE TITLE
Stream from different type of DataStructure

### ISSUE THREAD

**Issue by mmonti** [jeffbski/redis-rstream#6]
This is mainly a question rather than an issue. Can I use redis-rstream to stream data from a set structure in redis?
I am getting the following error when trying to stream from a set:
```
ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value
```
Thanks!

**Comment by jeffbski** [comment]
That's an interesting idea that could be added but library doesn't currently support it.

I'm happy to apply the PR if you want to add it. :-)
